name: OpenAPI Consistency Check

on:
  pull_request:
    paths:
      - "pkg/openapi/**/*"
      - ".github/workflows/openapi-check.yml"
      - "go.mod"
      - "go.sum"

jobs:
  check-openapi-consistency:
    name: Check OpenAPI Spec Consistency
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.0"

      - name: Run make generate
        run: make generate

      - name: Check for changes in pkg/openapi folder
        id: diff
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          openapi_changed=false
          if ! git diff --exit-code origin/$BRANCH_NAME -- "pkg/openapi/attestation/**/*"; then
            openapi_changed=true
          fi

          if [ "$openapi_changed" = "true" ]; then
            echo "diff_found=true" >> $GITHUB_OUTPUT
          else
            echo "diff_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail if openapi spec has changed
        if: ${{ steps.diff.outputs.diff_found == 'true' }}
        run: |
          echo "Error: One or more files in pkg/openapi/attestation/**/* have changed after running 'make generate'. Please commit the updated files."
          exit 1
